# HTTPRoute for MySpeed web UI
# Routes: myspeed.k8s.rommelporras.com â†’ myspeed Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: myspeed
  namespace: home
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: default
      sectionName: https
  hostnames:
    - myspeed.k8s.rommelporras.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: myspeed
          port: 5216
