# Tdarr HTTPRoute
# Routes: tdarr.k8s.rommelporras.com -> tdarr:8265 (WebUI)
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tdarr
  namespace: arr-stack
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: default
      sectionName: https
  hostnames:
    - "tdarr.k8s.rommelporras.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tdarr
          port: 8265
